id: A0554C666
title: Colophon
type: translation
source_metadata:
  languages:
  - zh
  - bo
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-01 23:45:56.574955
  last_modified_at: 2022-03-01 23:45:56.574960
