id: A0554C666
title: CVI_Verses 61-68
type: translation
source_metadata:
  languages:
  - zh
  - bo
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-01 23:45:56.233427
  last_modified_at: 2022-03-01 23:45:56.233433
