id: A0554C666
title: CXIV_Verses 101-107
type: translation
source_metadata:
  languages:
  - zh
  - bo
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-01 23:45:56.363687
  last_modified_at: 2022-03-01 23:45:56.363691
