id: A0554C666
title: CII_Verses 41-56
type: translation
source_metadata:
  languages:
  - zh
  - bo
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-01 23:45:56.066670
  last_modified_at: 2022-03-01 23:45:56.066676
