id: A0554C666
title: CIX_Verses 1-20
type: translation
source_metadata:
  languages:
  - zh
  - bo
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-01 23:45:56.105560
  last_modified_at: 2022-03-01 23:45:56.105564
