id: A0554C666
title: CXII_Verses 101-120
type: translation
source_metadata:
  languages:
  - zh
  - bo
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-01 23:45:56.326778
  last_modified_at: 2022-03-01 23:45:56.326784
