id: A0554C666
title: CXXVI_Verses 61-80
type: translation
source_metadata:
  languages:
  - zh
  - bo
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-01 23:45:56.532716
  last_modified_at: 2022-03-01 23:45:56.532719
