id: A0554C666
title: CI_Verses 81-89
type: translation
source_metadata:
  languages:
  - zh
  - bo
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-01 23:45:56.159493
  last_modified_at: 2022-03-01 23:45:56.159497
