id: A0554C666
title: CXXIII_Verses 21-40
type: translation
source_metadata:
  languages:
  - zh
  - bo
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-01 23:45:56.462116
  last_modified_at: 2022-03-01 23:45:56.462119
