id: A0554C666
title: CX_Verse 41
type: translation
source_metadata:
  languages:
  - zh
  - bo
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-01 23:45:56.559426
  last_modified_at: 2022-03-01 23:45:56.559429
