id: A0554C666
title: CXII_Verse 121
type: translation
source_metadata:
  languages:
  - zh
  - bo
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-01 23:45:56.314677
  last_modified_at: 2022-03-01 23:45:56.314681
